name: a2875cdc-ba6a-49dc-aab7-cdf7c4fc0fa8
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - jupyter
  - pandas
  - intake
  - intake-xarray
  - aiohttp
  - hvplot
  - xarray
  - pyhdf
  - cartopy
  - datashader
  - python-dotenv
  - pyresample
  - satpy
  - pyspectral